services:
  app:
    image: nguyenthietduydan/ntucoder:1.0
    container_name: api_app
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
        - ConnectionStrings__DatabaseConnection=server=db;database=ntucoder_db;user=root;password=12345;port=3306; 
    depends_on:
        - db
        - minio
    restart: always
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ntucoder_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio_container
    environment:
      MINIO_ROOT_USER: ntucoder
      MINIO_ROOT_PASSWORD: ntucoder
    ports:
      - "9000:9000"       # MinIO console
      - "9001:9001"       # MinIO browser
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  mysql_data:
  minio_data:
